version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type:chore"
      - "prio:low"
      - "status:review"
    reviewers:
      - "brenocq"
    assignees:
      - "brenocq"
