#version 450
layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba32f) uniform readonly image2D inputImage;// Equirectangular map
layout (binding = 1, rgba32f) uniform image2D outputImage;// Cubemap side

void main()
{   
    vec4 color = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y));
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(.1,.2,.8,1));
} 
