name: Atta CI CPU
on: [push, pull_request, release]

jobs:
  build:
    name: ${{ matrix.config.name }} - Build and Test
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          name: "Ubuntu Latest",
          os: ubuntu-latest,
          build_type: "Release"
        }
        - {
          name: "MacOS Latest",
          os: macos-latest,
          build_type: "Release"
        }
        - {
          name: "Windows Latest",
          os: windows-latest,
          build_type: "Release"
        }

    steps:
    - name: Checkout atta
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies on ubuntu
      if: startsWith(matrix.config.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build cmake xorg-dev
        ninja --version
        cmake --version
        gcc --version

    - name: Install dependencies on macos
      if: startsWith(matrix.config.os, 'macos')
      run: |
        brew install cmake ninja
        ninja --version
        cmake --version

    - name: Install dependencies on windows
      if: startsWith(matrix.config.os, 'windows')
      run: |
        choco install ninja cmake
        ninja --version
        cmake --version

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: cmake --build build --parallel --config ${{ matrix.config.build_type }}

    - name: Test
      run: ctest
      working-directory: build
