name: 🍎 MacOS

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run CI on"
        required: false
        default: main

jobs:
  build:
    name: ${{ matrix.config.name }} - Build and test
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { name: "MacOS Latest", os: macos-latest, build_type: "Release" }

    steps:
      - name: Checkout atta
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install cmake
          cmake --version

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: cmake --build build --parallel --config ${{ matrix.config.build_type }}

      - name: Test
        run: ctest
        working-directory: build
