name: 📋 Update README

on:
  workflow_dispatch: # Manual triggering
  issues: # Triggers on issue events
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled
      - assigned
      - unassigned
      - pinned
      - unpinned
  issue_comment: # Triggers on issue comment events
     types:
       - created
  push: # Triggers on push events

jobs:
  generate-svgs:
    name: Generate SVGs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r .github/scripts/readme_svgs/requirements.txt

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/readme_svgs/gen_status_cards.py
          python .github/scripts/readme_svgs/gen_issue_cards.py

      - name: Save generated SVGs temporarily
        run: |
          mkdir -p "$RUNNER_TEMP/tmp_svgs"
          cp *.svg "$RUNNER_TEMP/tmp_svgs/"

      - name: Create orphan branch and commit SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan generated-svgs
          git reset --hard
          git clean -fdx
          cp "$RUNNER_TEMP/tmp_svgs/"*.svg ./
          git add *.svg
          git commit -m "Auto-update README SVGs"

      - name: Push orphan branch
        run: git push --force origin generated-svgs
