name: Update readme buttons

on: push

jobs:
  update-images:
    name: Update images
    runs-on: ubuntu-latest
    env:
      working-directory: .github/scripts/updateReadmeButtons
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Decrypt secret
        working-directory: ${{env.working-directory}}
        env:
          SECRET_GCLOUD: ${{secrets.SECRET_GCLOUD}}
        run: ./decrypt_secret.sh

      - name: Setup python env
        working-directory: ${{env.working-directory}}
        run: pip install -r requirements.txt

      - name: Update gcloud images
        working-directory: ${{env.working-directory}}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        run: python updateReadmeButtons.py
