name: 🕸️ Web

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }} - Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { name: "Web Latest", os: ubuntu-latest, build_type: "Release" }

    steps:
      - uses: mymindstorm/setup-emsdk@v14

      - name: Checkout atta
        uses: actions/checkout@v5

      - name: Configure
        run: |
          mkdir build
          cd build
          emcmake cmake ..

      - name: Build
        run: cmake --build build --parallel --config ${{ matrix.config.build_type }}
