name: 🪟 Windows

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }} - Build and test
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { name: "Windows Latest", os: windows-latest, build_type: "Release" }

    steps:
      - name: Checkout atta
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install cmake
          cmake --version

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: cmake --build build --parallel --config ${{ matrix.config.build_type }}

      - name: Test
        run: ctest
        working-directory: build
